name: test-node-sdk

on:
  push:
    branches: [ main ]
    paths:
      - 'clients/sdk/backend/nodejs/**'
  pull_request:
    paths:
      - 'clients/sdk/backend/nodejs/**'
  workflow_dispatch:

jobs:
  node-sdk:
    name: build-node-sdk
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    defaults:
      run:
        working-directory: clients/sdk/backend/nodejs
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install & Build
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          npm run build
